server:
  port: 5030
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123
  mail:
    properties.mail.smtp.port: 587
    password: scnbktlewhjgebdh
    host: smtp.qq.com
    username: 2532601658@qq.com
    default-encoding: UTF-8
    nickname: 逝痕枫舞
    from: 2532601658@qq.com
  devtools:
    restart:
      enabled: true
  application:
    name: iblog-user
  cloud:
    nacos:
      discovery:
        server-addr: 81.70.169.127:8848
    sentinel:
      transport:
        dashboard: 81.70.169.127:8858
  datasource:
    url: jdbc:mysql://localhost:3306/eblog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true
# Feign对Sentinel的支持
feign:
  sentinel:
    enabled: true